
#{
#  "app": {
#    "port": "8322",
#    "upload_file_path": "e:\\golang\\www\\go-gin-chat\\tmp_images\\",
#    "cookie_key": "4238uihfieh49r3453kjdfg",
#    "serve_type": "GoServe",
#    "sm_token": "xxxxxxxxxxx",
#    "debug_mod": "true"
#  },
#  "mysql": {
#    "dsn": "admin:admin@tcp(127.0.0.1:3306)/go_gin_chat?charset=utf8mb4&parseTime=True&loc=Local"
#  }
#}

app:
  port: 8322
  upload_file_path: e:\\golang\\www\\go-gin-chat\\tmp_images\\
  cookie_key: 4238uihfieh49r3453kjdfg
  serve_type: GoServe
  sm_token: xxxxxxxxxxx
  debug_mod: true
mysql:
  dsn: root:mypassword.123@tcp(49.233.53.131:3307)/go_gin_chat?charset=utf8mb4&parseTime=True&loc=Local